# To regenerate:
# conda env export --from-history | head -n -1 > environment.yml
# (head -n -1 removes system-specific "prefix" attribute)
name: karpathy-nn-z2h
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - python=3.10
  - pytorch=1.13
